#!/bin/bash
git add .
echo "masukan pesan donk buat tanda di repo nya: "
read pesan
git commit -m "$pesan"
for a in $(cat .git/config | grep "\[remote" | cut -d" " -f2 | cut -d"\"" -f2);
do
      git push $a devel 
done
